name: _
publish_to: none

environment:
  sdk: '^3.8.0'

workspace:
  - translation_study_app_client
  - translation_study_app_server
  - translation_study_app_flutter
dependency_overrides:
  flutter_secure_storage: ^10.0.0

