services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: translation_study_app
      POSTGRES_PASSWORD: "m8MP202BgFcdmW31w6xqP6XDpZP52EF5"
    volumes:
      - translation_study_app_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "d8EMsLCBdUKynVLDMUmwh-Y0FE87shAh"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: translation_study_app_test
      POSTGRES_PASSWORD: "lAKX1Dzcgc6mDbX6xmGdis99msk-s3wq"
    volumes:
      - translation_study_app_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "gFKQkW6FYxvaLF0SkIiIlM3PJXBtXkZk"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  translation_study_app_data:
  translation_study_app_test_data:
